### ISSUE TITLE
一点疑问。data层与Android无关？

### ISSUE THREAD

**Issue by landryshuai** [bravekingzhang/CleanArch#1]
data层与android无关，如何拿数据，包括网络和本地存储？

**Comment by landryshuai** [comment]
而且，第二张图，难道不是android10 画的？怎么成了bob画的啦？

**Comment by bravekingzhang** [comment]
data层属于内层，不应该知道有andriod层的存在。拿网络数据等并非脱离android就做不了，而且一定可以做到，而且依据clean arch的思想，一定要脱离android层去做。第二张图应该是出自bob大叔那个视频。

**Comment by landryshuai** [comment]
@bravekingzhang 我个人的看法。数据和UI这两个都是和系统耦合度很高的东西。对于android来说，这两个模块不应该和android隔离。除了model层，他操作数据，处理业务逻辑。这个和android无关，是可取的。从android10写的例子来看，他的data层，也是个android库工程。

**Comment by bravekingzhang** [comment]
从android10写的例子来看，他的data层，也是个android库工程。我看到这句话，我就觉得没有必要再和你说什么了，真的，有些时候基本东西还是要学一下的。

**Comment by landryshuai** [comment]
@bravekingzhang 你不要激动。如果有什么冒犯你的地方，我先说声对不起。
我是个的菜鸟，现在在学习架构方面的知识，有很多不懂的地方，谢谢你指正出来。上面来提问题，其实就是探讨的意思。想和你学习一下，没有指责你的意思。

当然了，我肯定是愿意做模块隔离，否则我也不会和你讨论这么多。你会在一些特别简单的功能里面，都写一个接口，然后再写个实现，其他模块都基于这个接口去做开发？没有最好的架构，只有合适项目的架构。我个人的理解是，domain层做的就是业务层面的东西，与平台隔离。为什么在domain层提供自己操作的Repository的接口？个人感觉，作者的意思其实就是想把数据那边与平台相关的操作隔离开来。然后data做的就是数据的存取等动作。

当然啦，如果你还想在data层，再做一些特别多的逻辑，抽离出平台相关的代码，也是不错的选择。

以上是我的个人看法，有什么不对的地方，还是希望你能指正。

**Comment by bravekingzhang** [comment]
问题我关了哈，当我说了一些废话吧，不巧还被打上激动的标签了，你现在终于明白了data层与android无关是可以拿数据的了，做隔离是应该的，到这里已经算是解决你的问题了，如果还有问题，微信或者简书上交流。
