### ISSUE TITLE
clean architecture结构的分层位置问题

### ISSUE THREAD

**Issue by mawenge** [bravekingzhang/CleanArch#2]
我发现有两种分层的方法：
1、是在project下按照module分为data， domain， presentation三层
2、是在app这个主module下面分为三个包，我看楼主就是这样干的

那么哪一个比较好呢

**Comment by bravekingzhang** [comment]
没有谁对谁错，clean architecture 只不过是一种思想，目的是代码分层，结构更加清晰，可维护性更好，可测试性更高，两种都是OK的 ，只要团队的成员认可一种就行了，保持代码风格一致 :D

**Comment by mawenge** [comment]
谢谢，最近我也是又看了一些，觉得随着项目变大，还是按照module分比较好一些
