### ISSUE TITLE
为什么不用module的形式来组织三层？

### ISSUE THREAD

**Issue by Sloaix** [bravekingzhang/CleanArch#3]
为什么不用module的形式来组织三层？
Android-CleanArchitecture是这样做的，module之间的依赖，data和domain层就像android library一样，我个人也认为这样做结构会更清晰一点，而不是都写在一个module中。

**Comment by lsxiao** [comment]
为什么不用module的形式来组织三层？
Android-CleanArchitecture是这样做的，module之间的依赖，data和domain层就像android library一样，我个人也认为这样做结构会更清晰一点，而不是都写在一个module中。

**Comment by bravekingzhang** [comment]
可以的 ，只要记住，由外向内的依赖即可，不要存在交叉依赖这种耦合性比较高的情况即可 ，一个团队都用一个风格就好 。
